"use client";
import Image from "next/image";
import { useSearchParams } from "next/navigation";
import { useEffect, useMemo, useRef, useState } from "react";
import { encodeFunctionData } from "viem";
import { AmountAllocationControl } from "@/components/AmountAllocationControl";
import { useWallet } from "@/components/Wallet/WalletProvider";
import { bridgeChains, previewBridge, readSourceUsdcBalance, submitBridge } from "@/features/move/services/bridge";
import type { BridgePreview, BridgeStage, SourceChain } from "@/features/move/types";
import "./move-controls.css";
import "./move-modes.css";

const logo: Record<string,string>={Arc:"/images/chains/arc.png",Arbitrum:"/images/chains/arbitrum.png",Ethereum:"/images/chains/ethereum.png",Base:"/images/chains/base.png",Optimism:"/images/chains/optimism.png",Polygon:"/images/chains/polygon.png",Avalanche:"/images/chains/avalanche.png",Linea:"/images/chains/linea.png",Sei:"/images/chains/sei.png"};
const validAmount=(v:string)=>/^\d+(\.\d{1,6})?$/.test(v)&&Number(v)>0; const validRecipient=(v:string)=>/^0x[a-fA-F0-9]{40}$/.test(v); const decimals=(c:SourceChain)=>c.isArc?18:6; const fmt=(v?:bigint,d=6)=>v===undefined?"—":(Number(v)/10**d).toLocaleString("en-US",{maximumFractionDigits:3}); const parse=(v:string,d:number)=>{const[w,f=""]=v.split(".");return BigInt(w||"0")*10n**BigInt(d)+BigInt((f+"0".repeat(d)).slice(0,d));};
const abi=[{type:"function",name:"transfer",stateMutability:"nonpayable",inputs:[{name:"to",type:"address"},{name:"value",type:"uint256"}],outputs:[{name:"",type:"bool"}]}] as const;
function Logo({chain}:{chain?:SourceChain}){const src=chain&&logo[chain.name];return src?<Image className="move-network-logo" src={src} width={34} height={34} alt=""/>:null;}
function Select({label,value,chains,selected,balance,onChange}:{label:string;value:string;chains:SourceChain[];selected?:SourceChain;balance?:bigint;onChange:(v:string)=>void}){return <label className="route-network-field"><span>{label}</span><div className="route-network-choice"><Logo chain={selected}/><div><b>{selected?`${selected.name}${selected.isArc?" Mainnet":""}`:"Choose network"}</b><small>{fmt(balance,selected?decimals(selected):6)} USDC</small></div><span className="route-network-chevron"/><select aria-label={label} value={value} onChange={e=>onChange(e.target.value)}>{chains.map(c=><option key={c.name} value={c.name}>{c.name}{c.isArc?" Mainnet":""}</option>)}</select></div></label>;}
export function MoveBridge(){const{address,chainId,connect,provider}=useWallet();const search=useSearchParams();const chains=useMemo(()=>bridgeChains(),[]);const arc=chains.find(c=>c.isArc);const other=chains.find(c=>!c.isArc);const initial=chains.find(c=>c.name===search.get("from")&&!c.isArc)?.name??arc?.name??"";const[fromName,setFromName]=useState(initial);const[toName,setToName]=useState(initial===arc?.name?other?.name??"":arc?.name??"");const[mode,setMode]=useState<"bridge"|"send">("bridge");const[amount,setAmount]=useState("");const[recipient,setRecipient]=useState("");const[balance,setBalance]=useState<bigint>();const[preview,setPreview]=useState<BridgePreview>();const[stage,setStage]=useState<BridgeStage>("idle");const[review,setReview]=useState(false);const[sendState,setSendState]=useState<"idle"|"waiting"|"submitted">("idle");const[hash,setHash]=useState("");const[error,setError]=useState("");const inFlight=useRef(false);const from=chains.find(c=>c.name===fromName);const to=chains.find(c=>c.name===toName);const availableBalance=from&&address?balance:undefined;const correct=!!from&&chainId===from.chainId;const route=!!from&&!!to&&(from.isArc||to.isArc)&&from.name!==to.name;const tooHigh=!!from&&availableBalance!==undefined&&validAmount(amount)&&parse(amount,decimals(from))>availableBalance;
useEffect(()=>{let off=false;if(!from||!address)return;void readSourceUsdcBalance(from,address as `0x${string}`).then(v=>!off&&setBalance(v)).catch(()=>!off&&setError("Could not read the source-chain USDC balance."));return()=>{off=true;};},[from,address]);
const reset=()=>{setPreview(undefined);setStage("idle");setReview(false);setSendState("idle");setHash("");setError("");}; const allocation=(p:number)=>{if(!from||availableBalance===undefined)return;const d=decimals(from),b=10n**BigInt(d),v=availableBalance*BigInt(p)/100n;setAmount(`${v/b}.${(v%b).toString().padStart(d,"0").replace(/0+$/,"")}`.replace(/\.$/,""));reset();}; const switchNetwork=async()=>{if(from&&provider)await provider.request({method:"wallet_switchEthereumChain",params:[{chainId:`0x${from.chainId.toString(16)}`}]});};
const quote=async()=>{if(!address)return void connect();if(!from||!to||!route)return setError("One end of this Move route must be Arc Mainnet.");if(!validAmount(amount)||tooHigh)return setError("Enter a valid available USDC amount.");if(!correct)return setStage("wrongNetwork");if(!provider)return setError("Choose a wallet first.");setStage("preparingQuote");try{setPreview(await previewBridge(provider,from,to,amount));setStage("quoteReady");}catch{setStage("failed");setError("Route not available or live estimate failed.");}}; const confirmBridge=async()=>{if(!provider||!from||!to||!preview||inFlight.current)return;inFlight.current=true;setStage("waitingForWallet");try{const r=await submitBridge(provider,from,to,amount,()=>{});setStage(r.state==="success"?"completed":"failed");}catch{setStage("failed");setError("Bridge failed.");}finally{inFlight.current=false;}};
const send=async()=>{if(!address)return void connect();if(!from||!validAmount(amount)||!validRecipient(recipient)||tooHigh)return setError("Enter a valid recipient and available USDC amount.");if(!correct)return setError(`Switch the wallet to ${from.name} before sending.`);if(!review){setReview(true);return;}if(!provider||inFlight.current)return;inFlight.current=true;setSendState("waiting");try{const tx=await provider.request({method:"eth_sendTransaction",params:[{from:address,to:from.usdcAddress,value:"0x0",data:encodeFunctionData({abi,functionName:"transfer",args:[recipient as `0x${string}`,parse(amount,decimals(from))]})}]}) as string;setHash(tx);setSendState("submitted");}catch{setSendState("idle");setError("Send failed.");}finally{inFlight.current=false;}};
const amountField=<label className="move-amount-field">AMOUNT<div className="amount"><input value={amount} onChange={e=>{setAmount(e.target.value);reset();}} inputMode="decimal" placeholder="0.00"/><b>USDC</b></div><div className="move-amount-meta"><span>Balance: {fmt(availableBalance,from?decimals(from):6)} USDC</span><AmountAllocationControl percent={100} onPercent={allocation}/></div></label>;
return <div className="move-card"><div className="move-mode-tabs"><button className={mode==="bridge"?"active":""} onClick={()=>{setMode("bridge");reset();}}>Bridge</button><button className={mode==="send"?"active":""} onClick={()=>{setMode("send");reset();}}>Send</button></div>{mode==="bridge"?<><div className="route-selectors"><Select label="FROM" value={fromName} chains={chains} selected={from} balance={balance} onChange={v=>{setFromName(v);reset();}}/><button className="flip" onClick={()=>{setFromName(toName);setToName(fromName);reset();}}>⇄</button><Select label="TO" value={toName} chains={chains} selected={to} onChange={v=>{setToName(v);reset();}}/></div>{amountField}<section className="move-route"><p>Route</p><div className="move-route-line"><div className="move-route-network"><Logo chain={from}/><span><b>{from?.name}</b><small>USDC</small></span></div><div className="move-route-connector"><i/><strong>{preview?"CCTP":"Circle Bridge"}</strong><em>→</em></div><div className="move-route-network move-route-destination"><span><b>{to?.name}</b><small>USDC</small></span><Logo chain={to}/></div></div></section>{error&&<p className="error">{error}</p>}<p className="bridge-state">{stage==="quoteReady"?"Review the Move details below.":stage==="waitingForWallet"?"Waiting for wallet confirmation…":"Enter the amount you want to move."}</p><div className="move-actions">{!address?<button className="wallet" onClick={()=>void connect()}>Connect wallet</button>:!correct?<button className="switch" onClick={()=>void switchNetwork()}>Switch to {from?.name}</button>:<button className="wallet" disabled={!route||!validAmount(amount)||tooHigh||stage==="waitingForWallet"} onClick={()=>void(preview?confirmBridge():quote())}>{stage==="waitingForWallet"?"Waiting for wallet…":preview?"Confirm Move":"Move"}</button>}</div></>:<><Select label="NETWORK" value={fromName} chains={chains} selected={from} balance={balance} onChange={v=>{setFromName(v);reset();}}/><label className="send-recipient-field">RECIPIENT<input value={recipient} onChange={e=>{setRecipient(e.target.value);reset();}} placeholder="0x…"/></label>{amountField}{review&&<section className="preview"><h2>Review Send</h2><div className="move-review-row"><span>Recipient</span><b>{recipient}</b></div><div className="move-review-row"><span>Amount</span><b>{amount} USDC</b></div></section>}{hash&&<p className="send-state">Submitted: {hash}</p>}{error&&<p className="error">{error}</p>}<div className="move-actions"><button className="wallet" disabled={sendState!=="idle"||!validAmount(amount)||!validRecipient(recipient)||tooHigh} onClick={()=>void send()}>{sendState==="waiting"?"Waiting for wallet…":sendState==="submitted"?"Submitted":review?"Confirm Send":"Review Send"}</button></div></>}</div>;}
