import { smartPeriod, smartNextCheck } from "./engine.ts";
import type { AutomationActivity, AutomationPlan, AutomationStore } from "../types.ts";
const KEY = "stabio-autopilot-v1";
const empty = (): AutomationStore => ({ version: 2, plans: [], activity: [] });
type LegacyPlan = Record<string, unknown>;
function migratePlan(value: LegacyPlan): AutomationPlan | undefined { if (value.strategy === "scheduled_dca" || value.strategy === "smart_dca") return value as AutomationPlan; if (typeof value.id !== "string" || typeof value.amount !== "string" || typeof value.frequency !== "string") return undefined; const now = new Date(); const base = { id: value.id, name: typeof value.name === "string" ? value.name : "BTC DCA", sourceAsset: "USDC" as const, targetAsset: "cirBTC" as const, amount: value.amount, maxSlippage: typeof value.maxSlippage === "string" ? value.maxSlippage : "1", maxFee: typeof value.maxFee === "string" ? value.maxFee : "0.50", totalBudget: typeof value.totalBudget === "string" ? value.totalBudget : value.amount, spentBudget: typeof value.spentBudget === "string" ? value.spentBudget : "0", status: value.status === "paused" ? "paused" as const : "active" as const, createdAt: typeof value.createdAt === "string" ? value.createdAt : now.toISOString(), nextCheckAt: typeof value.nextCheckAt === "string" ? value.nextCheckAt : now.toISOString(), executions: typeof value.executions === "number" ? value.executions : 0, skipped: typeof value.skipped === "number" ? value.skipped : 0, history: Array.isArray(value.history) ? value.history : [], lastState: "waiting" as const, lastReason: "Migrated from Autopilot V1." };
  const condition = value.condition as { period?: number; timeframe?: "1D" | "4H" | "1H"; operator?: "below" | "above"; threshold?: string } | undefined;
  if (condition?.threshold) { const period = value.frequency === "daily" ? "daily" : "weekly"; const bounds = smartPeriod(now, period); return { ...base, strategy: "smart_dca", smart: { period, checkIntervalMinutes: 60, condition: { type: "rsi", asset: "BTC/USD", period: condition.period ?? 14, timeframe: condition.timeframe ?? "1D", operator: condition.operator ?? "below", threshold: condition.threshold }, maxPurchasesPerPeriod: 1, ...bounds, purchasesThisPeriod: 0 }, nextCheckAt: smartNextCheck(now, 60) }; }
  return { ...base, strategy: "scheduled_dca", schedule: { frequency: value.frequency === "daily" ? "daily" : "weekly", dayOfWeek: typeof value.dayOfWeek === "number" ? value.dayOfWeek : 1, time: typeof value.time === "string" ? value.time : "09:00", timezone: typeof value.timezone === "string" ? value.timezone : "UTC" } };
}
export function normalizeAutomationStore(value: unknown): AutomationStore { if (!value || typeof value !== "object") return empty(); const parsed = value as { version?: number; plans?: unknown[]; activity?: AutomationActivity[] }; if (!Array.isArray(parsed.plans) || !Array.isArray(parsed.activity)) return empty(); if (parsed.version === 2) return { version: 2, plans: parsed.plans as AutomationPlan[], activity: parsed.activity }; if (parsed.version === 1) { const plans = parsed.plans.map((plan) => migratePlan(plan as LegacyPlan)).filter((plan): plan is AutomationPlan => Boolean(plan)); return { version: 2, plans, activity: parsed.activity }; } return empty(); }
export function loadAutomationStore(): AutomationStore { if (typeof window === "undefined") return empty(); try { return normalizeAutomationStore(JSON.parse(window.localStorage.getItem(KEY) ?? "")); } catch { return empty(); } }
export function saveAutomationStore(store: AutomationStore) { window.localStorage.setItem(KEY, JSON.stringify(store)); }
