"use client";

import { createContext, useCallback, useContext, useEffect, useMemo, useState } from "react";
import { createPublicClient, http } from "viem";
import { ARC_MAINNET, arcWalletChain } from "@/config/chains";

export type Eip1193Provider = NonNullable<Window["ethereum"]>;
export type WalletOption = { id: string; name: string; icon?: string; provider: Eip1193Provider };
type WalletState = { address?: string; chainId?: number; balance?: bigint; error?: string; isConnecting: boolean; provider?: Eip1193Provider; wallets: WalletOption[]; connect: (walletId?: string) => Promise<void>; disconnect: () => void; switchToArc: () => Promise<void>; };
type AnnouncedProvider = { info?: { uuid?: string; name?: string; icon?: string; rdns?: string }; provider?: Eip1193Provider };
const WalletContext = createContext<WalletState | null>(null);
const publicClient = createPublicClient({ transport: http(ARC_MAINNET.rpcUrl) });
const hexToNumber = (value: unknown) => typeof value === "string" ? Number.parseInt(value, 16) : undefined;
const fallbackName = (provider: Eip1193Provider) => (provider as { isMetaMask?: boolean; isRabby?: boolean; isOkxWallet?: boolean }).isRabby ? "Rabby Wallet" : (provider as { isMetaMask?: boolean }).isMetaMask ? "MetaMask" : (provider as { isOkxWallet?: boolean }).isOkxWallet ? "OKX Wallet" : "Browser Wallet";

export function WalletProvider({ children }: { children: React.ReactNode }) {
  const [address, setAddress] = useState<string>(); const [chainId, setChainId] = useState<number>(); const [balance, setBalance] = useState<bigint>(); const [error, setError] = useState<string>(); const [isConnecting, setIsConnecting] = useState(false); const [wallets, setWallets] = useState<WalletOption[]>([]); const [provider, setProvider] = useState<Eip1193Provider>();
  const refresh = useCallback(async (nextAddress?: string, nextChainId?: number) => { setAddress(nextAddress); setChainId(nextChainId); setBalance(undefined); if (nextAddress && nextChainId === ARC_MAINNET.id) try { setBalance(await publicClient.getBalance({ address: nextAddress as `0x${string}` })); } catch { setError("Could not read the Arc USDC balance from the Arc RPC."); } }, []);
  const addWallet = useCallback((wallet: WalletOption) => setWallets((items) => items.some((item) => item.id === wallet.id || item.provider === wallet.provider) ? items : [...items, wallet]), []);
  useEffect(() => { const announce = (event: Event) => { const detail = (event as CustomEvent<AnnouncedProvider>).detail; const next = detail?.provider; if (next) addWallet({ id: detail?.info?.uuid ?? detail?.info?.rdns ?? fallbackName(next), name: detail?.info?.name ?? fallbackName(next), icon: detail?.info?.icon, provider: next }); }; window.addEventListener("eip6963:announceProvider", announce); window.dispatchEvent(new Event("eip6963:requestProvider")); const fallbackTimer = window.setTimeout(() => { const fallback = window.ethereum as (Eip1193Provider & { providers?: Eip1193Provider[] }) | undefined; for (const item of fallback?.providers ?? (fallback ? [fallback] : [])) addWallet({ id: fallbackName(item), name: fallbackName(item), provider: item }); }, 0); return () => { window.removeEventListener("eip6963:announceProvider", announce); window.clearTimeout(fallbackTimer); }; }, [addWallet]);
  const connect = useCallback(async (walletId?: string) => { const selected = walletId ? wallets.find((wallet) => wallet.id === walletId)?.provider : provider ?? (wallets.length === 1 ? wallets[0].provider : undefined); if (!selected) { setError(wallets.length ? "Choose a wallet from Connect Wallet first." : "No EVM wallet was detected. Install or unlock a compatible browser wallet."); return; } setIsConnecting(true); setError(undefined); try { const accounts = await selected.request({ method: "eth_requestAccounts" }) as string[]; const currentChain = hexToNumber(await selected.request({ method: "eth_chainId" })); setProvider(selected); await refresh(accounts[0], currentChain); } catch (cause) { setError(cause instanceof Error ? cause.message : "Wallet connection was cancelled or failed."); } finally { setIsConnecting(false); } }, [provider, refresh, wallets]);
  const disconnect = useCallback(() => { setAddress(undefined); setChainId(undefined); setBalance(undefined); setError(undefined); setProvider(undefined); }, []);
  const switchToArc = useCallback(async () => { if (!provider) return setError("Choose and connect a wallet first."); setError(undefined); try { await provider.request({ method: "wallet_switchEthereumChain", params: [{ chainId: ARC_MAINNET.hexId }] }); } catch (cause) { if ((cause as { code?: number }).code !== 4902) return setError(cause instanceof Error ? cause.message : "Could not switch to Arc."); try { await provider.request({ method: "wallet_addEthereumChain", params: [arcWalletChain] }); } catch (addCause) { setError(addCause instanceof Error ? addCause.message : "Could not add Arc to the wallet."); } } }, [provider]);
  useEffect(() => { if (!provider) return; const accounts = (items: unknown) => { const next = Array.isArray(items) && typeof items[0] === "string" ? items[0] : undefined; void refresh(next, chainId); }; const chain = (next: unknown) => void refresh(address, hexToNumber(next)); provider.on?.("accountsChanged", accounts); provider.on?.("chainChanged", chain); return () => { provider.removeListener?.("accountsChanged", accounts); provider.removeListener?.("chainChanged", chain); }; }, [address, chainId, provider, refresh]);
  const value = useMemo(() => ({ address, chainId, balance, error, isConnecting, provider, wallets, connect, disconnect, switchToArc }), [address, balance, chainId, connect, disconnect, error, isConnecting, provider, switchToArc, wallets]);
  return <WalletContext.Provider value={value}>{children}</WalletContext.Provider>;
}
export function useWallet() { const value = useContext(WalletContext); if (!value) throw new Error("useWallet must be used inside WalletProvider"); return value; }
