const contents = [["Overview", "overview"], ["Portfolio", "portfolio"], ["Move", "move"], ["Earn", "earn"], ["Swap", "swap"], ["Payment & Automation", "payment-&-automation"], ["Agents", "agents"], ["Security", "security"], ["Technology", "technology"], ["FAQ", "faq"]] as const;

export default function HelpPage() {
  return <section className="about-page">
    <header className="about-intro"><p className="eyebrow">ABOUT STABIO FLOW</p><h1>Stablecoin operations, with your wallet in control.</h1><p>Stabio Flow is a non-custodial Arc application for viewing supported assets, moving and sending USDC, accessing Earn vaults, swapping supported assets, and managing payment and automation workflows.</p></header>
    <div className="about-callout"><b>Wallet-controlled by design</b><span>Stabio Flow never stores private keys or seed phrases. Any onchain transaction is reviewed and signed in your connected wallet.</span></div>
    <div className="about-layout">
      <aside className="about-toc" aria-label="Table of contents"><p>On this page</p><nav>{contents.map(([label, id]) => <a href={`#${id}`} key={id}>{label}</a>)}</nav></aside>
      <article className="about-content">
        <DocSection id="overview" title="What is Stabio Flow?"><p>Stabio Flow brings Arc-focused stablecoin operations into one interface. It is an active-development, non-custodial application: the connected wallet remains responsible for every transaction authorization.</p><ul><li><b>Dashboard</b> reads supported balances across configured networks and presents a portfolio overview.</li><li><b>Move</b> bridges USDC between Arc and supported networks, or sends USDC to another wallet.</li><li><b>Earn</b> discovers eligible USDC and EURC vaults on Arc and supports position management.</li><li><b>Swap</b> requests live Arc quotes for USDC, EURC, and cirBTC routes.</li><li><b>Payment &amp; Automation</b> contains Autopilot, payment requests, payment activity, and planned agent capabilities.</li></ul></DocSection>
        <DocSection id="portfolio" title="Portfolio"><p>The Dashboard reads the configured native asset and USDC balance for the connected address on supported networks. It does not claim to discover every token held by the wallet.</p><h3>Valuation</h3><p>Balance reads and USD prices are separate. Stabio first uses available Arc App Kit rates, then a CoinGecko fallback. An unavailable price is displayed as <code>$ —</code>; it does not mean the asset balance is zero.</p><p><b>Partial valuation</b> means only assets with a currently available USD rate are included in the portfolio value. Unified Balance is not included in the portfolio calculation.</p></DocSection>
        <DocSection id="move" title="Move"><h3>Bridge</h3><p>Bridge supports USDC routes where either the source or destination is Arc. The selected FROM and TO network balances are read independently for the connected address.</p><div className="about-flow"><span>Supported USDC network</span><i>↓</i><b>Bridge</b><i>↓</i><span>Arc or a supported network</span></div><p>Before confirmation, Stabio requests a live bridge estimate through Circle Arc App Kit. The wallet must be on the source chain and signs every protocol transaction. Route availability, fees, and completion depend on the returned SDK flow.</p><h3>Send</h3><p>Send transfers USDC from the selected network to a recipient address. It has no destination-network selector or bridge route; users review the recipient and amount before the connected wallet is asked to submit the transfer.</p></DocSection>
        <DocSection id="earn" title="Earn"><p>Earn discovers USDC and EURC vault opportunities returned by Arc App Kit. The interface supports vault discovery, position reads, deposit and withdrawal previews, and wallet-confirmed transactions where the vault supports them.</p><p>APY, availability, and withdrawal conditions are provided by the vault or SDK and can change. Stabio does not guarantee yield, liquidity, or withdrawal availability.</p><div className="about-risk"><b>Risk reminder</b><span>Vaults carry smart-contract, protocol, liquidity, and market risks. Review each transaction in your wallet before approving it.</span></div></DocSection>
        <DocSection id="swap" title="Swap"><p>Swap requests a live Arc App Kit quote for supported USDC, EURC, and cirBTC routes. Balances are read from Arc for the selected assets.</p><div className="about-flow horizontal"><span>Select assets</span><i>→</i><span>Enter amount</span><i>→</i><span>Live quote</span><i>→</i><span>Review</span><i>→</i><span>Wallet confirmation</span></div><p>The quote is cleared when relevant inputs change. If the SDK does not provide a route, price impact, or fee, Stabio shows that field as unavailable instead of inventing a value.</p></DocSection>
        <DocSection id="payment-&-automation" title="Payment & Automation"><h3>Autopilot</h3><p>Autopilot creates local scheduled or RSI-based USDC-to-cirBTC DCA plans. Plans are stored in the browser and are evaluated only while Stabio is open and the user checks them. A ready plan still requests a fresh live quote and requires the user to confirm the wallet transaction. It does not trade in the background or use delegated signing.</p><h3>Request Payment</h3><p>Payment Links and Invoices create local USDC payment requests for Arc Mainnet, with a shareable URL and QR code. Request data is stored in the browser and contains no keys or signatures.</p><h3>Payment Activity</h3><p>Payment Activity lists locally created payment requests and their status. This V1 does not submit a payment or independently verify an incoming transaction, so a request remains waiting until a reliable verifier is integrated.</p></DocSection>
        <DocSection id="agents" title="Agents"><p>The Agents area presents future Arc-oriented capabilities. Each card is currently informational and marked <b>Coming soon</b>; no agent is active, has a wallet, holds a balance, or can initiate a transaction in this version.</p><div className="about-tech"><div><b>Payment Agent</b><span>Prepare payment requests and monitor their status.</span></div><div><b>Treasury Agent</b><span>Track USDC balances and suggest funding routes.</span></div><div><b>Yield Agent</b><span>Monitor Earn positions and vault opportunities.</span></div><div><b>Risk Agent</b><span>Flag limits, failed routes, and unusual activity.</span></div><div><b>Settlement Agent</b><span>Reconcile invoices, receipts, and onchain payments.</span></div><div><b>Service Agent</b><span>Support usage-based USDC payments for services.</span></div></div><p>When implemented, any agent action should be governed by an explicit policy, budget, and audit trail. Stabio will preserve wallet confirmation for actions outside an approved, narrowly scoped policy.</p></DocSection>
        <DocSection id="security" title="Security & custody"><h3>Non-custodial</h3><p>Stabio does not store seed phrases, private keys, or an autonomous signing authority. Your wallet remains responsible for transaction authorization.</p><h3>Read-only data</h3><p>Portfolio balances, vault discovery, positions, and market data are read without custody transfer. RPC or market-data availability can affect what is shown.</p><h3>Transactions</h3><p>Move, Deposit, Withdraw, and Swap use the connected wallet and the relevant implemented SDK flow. Always inspect the network, amount, recipient, and fees in the wallet before signing.</p></DocSection>
        <DocSection id="technology" title="Technology"><div className="about-tech"><div><b>Frontend</b><span>Next.js, React, TypeScript</span></div><div><b>Wallet & chain access</b><span>Browser EIP-1193 wallet provider and viem</span></div><div><b>Arc integration</b><span>Arc Mainnet, Circle Arc App Kit, and Circle’s viem adapter</span></div><div><b>Portfolio</b><span>Public RPC reads, configured USDC contracts, and rate fallbacks</span></div><div><b>Market data</b><span>Arc App Kit rates and CoinGecko fallback data</span></div><div><b>Flows storage</b><span>Versioned browser local storage; no backend payment verifier in V1</span></div></div></DocSection>
        <DocSection id="faq" title="FAQ"><dl className="about-faq"><div><dt>Does Stabio Flow hold my funds?</dt><dd>No. Stabio does not custody assets or store wallet secrets.</dd></div><div><dt>Does Autopilot trade automatically?</dt><dd>No. It evaluates local plans while the app is open, then requires a fresh quote and wallet confirmation.</dd></div><div><dt>Are payment links already payment processing?</dt><dd>No. They create local Arc USDC payment requests and QR/share links. This version does not submit or independently verify payment transactions.</dd></div><div><dt>Why is a portfolio asset unvalued?</dt><dd>The balance may be known while an applicable USD rate is unavailable.</dd></div><div><dt>Are vault APYs guaranteed?</dt><dd>No. APY and liquidity are variable and depend on the underlying vault.</dd></div><div><dt>Does Stabio show every wallet token?</dt><dd>No. It reads assets supported by the current application configuration.</dd></div></dl></DocSection>
      </article>
    </div>
  </section>;
}

function DocSection({ id, title, children }: { id: string; title: string; children: React.ReactNode }) {
  return <section id={id} className="about-section"><h2>{title}</h2>{children}</section>;
}
